### ISSUE TITLE
下载代码导入idea后，运行项目出现Whitelabel Error Page

### ISSUE THREAD

**Issue by raking96** [ballcat-projects/ballcat-codegen#20]
master和1.4.0分支都试过，均提示这个。
readme中有提到执行启动脚本，但是只在bat下找到了一个start.bat，正常执行情况下 因为utf-8编码导致输出乱码，切换到gbk后无法执行。
随后在idea配置数据库后启动，访问localhost:7777，页面打开后提示Whitelabel Error Page

**Comment by Hccake** [comment]
如果需要只启动后台就访问页面，必须先在父工程目录下执行一次 mvn clean package。
打包时会自动将前端页面构建并置入服务端模块下。

**Comment by raking96** [comment]
感谢，确实是执行mvn clean package的问题 没注意到执行失败了。执行过mvn spring-javaformat:apply后正常打开项目了
